### ISSUE TITLE
Proposal: the update of User lastSeenAt & lastVisitAt in auth middleware should be optimized

### ISSUE THREAD

**Issue by yunge** [cellajs/cella#83]
In auth middleware, the update of User lastSeenAt & lastVisitAt is too frequent, it's better to "update after a certain amount of time past the old timestamp".

Unnecessary updates can affect postgres performance and generate unnecessary WAL logs.

And the code is in "backend/src/middlewares/guard/auth.ts", thanks.

**Comment by flipvh** [comment]
You are right. For counts in a high concurrency scenario we need a better count strategy altogether perhaps. Not directly on the user perhaps. This is an almost universal challenge, so I am sure that there exist smart solutions to have scalable counts that are almost realtime or eventually consistent? Perhaps an open source event analytics library can help cella to also maintain county like these? For example, I am following this repo: https://github.com/Openpanel-dev/openpanel . What do you think?

**Comment by flipvh** [comment]
benefit of such a strategy is that it can help with both app-level reporting as well as customer/tenant-level and perhaps product/project level reporting. cc @yunge

**Comment by yunge** [comment]
It's nice to have a more professional service, but I'd recommend keeping a basic functionality based on our own DB server.

After all, not everyone needs a professional paid service, such as in-house systems.

**Comment by flipvh** [comment]
Ok i changed it. It for now only updates lastVisitAt on GET /me only, so basically once per session. LastSeenAt is now not being used until we have a background process in place to handle events like these without affecting more critical events and requests. How are you btw? Still interested in cella? Its taking longer to get it stable, sorry about that. But I think we are getting there.
